@startuml
autonumber

actor       User
participant "User" as User

box "Merchant" #LightYellow
participant "Merchant APP" as MerchantAPP
participant "Merchant Backend" as MerchantBackend
end box

box "Easypaisa" #LightBlue
participant "EP H5" as EPH5 #LightGreen
participant "EP App" as EPApp #LightGreen
participant "EP Backend" as EPBackend #LightGreen
end box

== User Binding Flow ==
User -> MerchantAPP: click the signing agreement button
activate MerchantAPP
MerchantAPP -> MerchantBackend: Add Easypaisa payment method
activate MerchantBackend
MerchantBackend -> EPBackend: <font color=#f7a98d><b> Step1: Get PaymentAuthCode via /v2/authorizations/getPaymentAuthCode
activate EPBackend
EPBackend --> MerchantBackend: Response authUrl
deactivate EPBackend
MerchantBackend --> MerchantAPP: Response authUrl
deactivate MerchantBackend
deactivate MerchantAPP

alt If EPApp installed
MerchantAPP -> EPH5: <font color=#f7a98d><b> Step2: Open authUrl(H5 middle page)
activate MerchantAPP
activate EPH5
EPH5 -> EPH5: Show middle page
EPH5 -> EPApp: Open EP App
deactivate EPH5
activate EPApp
deactivate EPBackend
EPApp -> EPApp: Show sign page
User -> EPApp: Confirmation of agreement

EPApp -> EPBackend: Sign agreement
activate EPBackend
EPBackend --> EPApp: Response paymentAuthCode
deactivate EPBackend

EPApp --> MerchantAPP: Jump back to MerchantAPP with paymentAuthCode and authState
deactivate MerchantAPP
deactivate EPApp
end

alt If EPApp not installed
MerchantAPP -> EPH5: <font color=#f7a98d><b> Step2: Open authUrl(H5 middle page)
activate MerchantAPP
activate EPH5
EPH5 -> EPH5: Show middle page
EPH5 -> EPH5: Show sign page
User -> EPH5: Confirmation of agreement

EPH5 -> EPBackend: Sign agreement
activate EPBackend
EPBackend --> EPH5: Response paymentAuthCode
deactivate EPBackend

EPH5 --> MerchantAPP: Jump back to MerchantAPP with paymentAuthCode and authState
deactivate MerchantAPP
deactivate EPH5
end

MerchantAPP -> MerchantBackend: Apply paymentToken(paymentAuthCode)
activate MerchantAPP
activate MerchantBackend
MerchantBackend -> EPBackend: <font color=#f7a98d><b> Step3: Apply paymentToken via /v2/authorizations/getPaymentToken
activate EPBackend
EPBackend --> MerchantBackend: Response paymentToken(pinLessToken‘s business name)
deactivate EPBackend
MerchantBackend -> MerchantBackend: Save paymentToken
MerchantBackend --> MerchantAPP: Return success
deactivate MerchantBackend
deactivate MerchantAPP

== User Payment Flow ==
User -> MerchantAPP: Open cashier page
activate MerchantAPP
MerchantAPP -> MerchantBackend: Initiate pre-check
activate MerchantBackend
MerchantBackend -> EPBackend: <font color=#f7a98d><b> Step4: Pre Check payment via  /v2/payments/preCheck

activate EPBackend
EPBackend --> MerchantBackend: Response query result
deactivate EPBackend
MerchantBackend --> MerchantAPP: Response query result
deactivate MerchantBackend
MerchantAPP --> User:Displays available payment options
deactivate MerchantAPP

User -> MerchantAPP: Choose to pay with EasyPaisa
activate MerchantAPP
MerchantAPP -> MerchantBackend: Pay with EP and orderInfo(paymentOrderID,merchanetID,paymentAmount,paymentToken...)
activate MerchantBackend
MerchantBackend -> MerchantBackend: Risk check

MerchantBackend -> EPApp: <font color=#f7a98d><b> Step5: Create payment order via /v2/payments/createPayment
activate EPApp
EPApp -> EPBackend: Request payment
activate EPBackend
EPBackend --> EPApp: Response payment result
deactivate EPBackend
EPApp --> MerchantBackend: Response payment result
deactivate EPApp

MerchantBackend -> EPBackend: <font color=#f7a98d><b> Step6: Inquery payment result via /v2/payments/queryPayment
activate EPBackend
EPBackend --> MerchantBackend: Response query result
deactivate EPBackend
MerchantBackend --> MerchantAPP: Response query result
deactivate MerchantBackend
MerchantAPP --> User: Displaying payment results
deactivate MerchantAPP

== User Unbinding Flow ==
User -> MerchantAPP:User unbind agreement
activate MerchantAPP
MerchantAPP -> MerchantBackend: Send the unbinding request(params:paymentToken,mobileAccountNo)
activate MerchantBackend
MerchantBackend -> EPApp: <font color=#f7a98d><b> Step1: unbind agreement via /v2/authorizations/unbinding
activate EPApp
EPApp -> EPBackend : Request unbind
activate EPBackend
EPBackend --> EPApp: Response result
deactivate EPBackend
EPApp --> MerchantBackend: Response result
deactivate EPApp
MerchantBackend --> MerchantAPP: Response result
deactivate MerchantBackend
MerchantAPP-->"User": Response result
deactivate MerchantAPP

== User refund Flow ==
User -> MerchantAPP: Refund order
MerchantAPP -> MerchantBackend: Initiate refund request
activate MerchantBackend
MerchantBackend -> EPBackend:<font color=#f7a98d><b> Step1: refund order via /v2/refund/merchantRefund

activate EPBackend
EPBackend --> MerchantBackend: Response refund result
deactivate EPBackend
MerchantBackend --> MerchantAPP: Response refund result
deactivate MerchantBackend
MerchantAPP --> User:Displaying refund result
deactivate MerchantAPP
autonumber

@enduml
